const express = require("express");
const router = express.Router();
const  {upload} = require("../../middlewares/fileUpload");
const {verifyTokenAndAdmin} = require("../../middlewares/auth");
const {uploadBannerImage,getAllBannerImage,deleteBannerImage,updateBannerImage,getAllBanner,getOnebanner,updateImage,getAllfile}= require("../controllers/banner");
router.post("/banner",verifyTokenAndAdmin,upload,uploadBannerImage);
router.get("/getBanner",verifyTokenAndAdmin,getAllBannerImage);
router.delete("/deleteBanner/:id",verifyTokenAndAdmin,deleteBannerImage);
router.put("/updateBannerImage/:id",verifyTokenAndAdmin,upload,updateBannerImage);
router.get("/getOnebanner/:id",verifyTokenAndAdmin,getOnebanner);
router.get("/findBanner",getAllBanner);
router.post("/file",upload,updateImage);
router.get("/all",getAllfile);
module.exports = router;